$(call PKG_INIT_BIN, $(if $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON),0.2.20,0.4.1))
$(PKG)_SOURCE_DOWNLOAD_NAME_ABANDON:=$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE_DOWNLOAD_NAME_CURRENT:=v$($(PKG)_VERSION).tar.gz
$(PKG)_SOURCE_DOWNLOAD_NAME:=$($(PKG)_SOURCE_DOWNLOAD_NAME_$(if $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON),ABANDON,CURRENT))
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH_ABANDON:=b7b2978c3197aef0a6531f1cf0ee1aebb32a55ad8bda43064ce3a944edbcac83
$(PKG)_HASH_CURRENT:=e54e302a31d7ff4197ea6c77742b791d6ea508e0c60c955795f5195f0bec2edc
$(PKG)_HASH:=$($(PKG)_HASH_$(if $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON),ABANDON,CURRENT))
$(PKG)_SITE:=https://github.com/umurmur/umurmur/archive/refs/tags
### WEBSITE:=https://umurmur.net/
### MANPAGE:=https://github.com/umurmur/umurmur/wiki
### CHANGES:=https://github.com/umurmur/umurmur/releases
### CVSREPO:=https://github.com/umurmur/umurmur
### STEWARD:=fda77

$(PKG)_BINARY:=$($(PKG)_DIR)/src/umurmurd
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/umurmurd

ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON)),y)
$(PKG)_CONFIGURE_PRE_CMDS += ./autogen.sh;
else
$(PKG)_DEPENDS_ON += cmake-host

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX=/
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=Yes
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_UMURMUR_MONITOR=Off

endif

$(PKG)_CONDITIONAL_PATCHES+=$(if $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON),abandon,current)

$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_UMURMUR_OPENSSL
$(PKG)_REBUILD_SUBOPTS += FREETZ_PACKAGE_UMURMUR_MBEDTLS

$(PKG)_DEPENDS_ON += libconfig protobuf-c

ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_OPENSSL)),y)
$(PKG)_REBUILD_SUBOPTS += FREETZ_OPENSSL_SHORT_VERSION
$(PKG)_DEPENDS_ON += openssl
ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON)),y)
$(PKG)_CONFIGURE_OPTIONS += --with-ssl=openssl
else
$(PKG)_CONFIGURE_OPTIONS += -DSSL=openssl
$(PKG)_CONFIGURE_OPTIONS += -DOPENSSL_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
endif
endif

ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_MBEDTLS)),y)
$(PKG)_DEPENDS_ON += mbedtls
ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON)),y)
$(PKG)_CONFIGURE_OPTIONS += --with-ssl=mbedtls
else
$(PKG)_CONFIGURE_OPTIONS += -DSSL=mbedtls
$(PKG)_CONFIGURE_OPTIONS += -DMBEDTLS_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
endif
endif


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
ifeq ($(strip $(FREETZ_PACKAGE_UMURMUR_VERSION_ABANDON)),y)
$(PKG_CONFIGURED_CONFIGURE)
else
$(PKG_CONFIGURED_CMAKE)
endif

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(UMURMUR_DIR)
#cmake	cd $(UMURMUR_DIR) && cmake -LA .

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(UMURMUR_DIR) clean
	$(RM) $(UMURMUR_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(UMURMUR_TARGET_BINARY)

$(PKG_FINISH)
