name: image_firmware

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/image_firmware.yml'
      - '.github/docker/firmware/*'
  schedule:
    - cron: '45 18 28 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.repository == 'freetz-ng/freetz-ng'

    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: prepare
        id: prepare
        run: |
          OWNER="freetz-ng"
          IMAGE="$(echo "${{ github.workflow }}" | sed 's/.*_//')"
          URI="ghcr.io/$OWNER/internal/$IMAGE"
          echo "uri=$URI" >> $GITHUB_OUTPUT
          for x in Dockerfile entrypoint.sh; do ln -s .github/docker/$IMAGE/$x; done
          echo "################################################################" && echo "URI=$uri"

      - name: login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.FREETZ_DLTOKEN }}

      - name: docker
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prepare.outputs.uri }}:latest


