name: ufo-clean

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  ufo:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        box: ["5690", "7270", "7490"]
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v6

    - run: tools/prerequisites install

    - run: cp config-${{ matrix.box }} .config

    #- run: cp make/kernel/configs/avm/config-alder-4690_08.21 make/kernel/configs/freetz/config-alder-4690_08.21
    #- run: patch -p1 make/kernel/configs/freetz/config-alder-4690_08.21 < make/kernel/configs/diffs/config-alder-4690_08.21.diff

    #- run: KBUILD_SYMTYPES=1 make
    
    #- run: find . -name '*.symtypes' -exec bash -c 'f={}; sed "s/^/override /" $f > ${f%.symtypes}.symref' \;
    #- run: git checkout make/kernel/configs/freetz/config-alder-4690_08.21
    #- run: rm images/* || true

    - run: mkdir -p source/kernel/ref-alder-4690_08.21/linux-5.4

    - run: cp -r make/kernel/configs/symref/symref-alder-4690_08.21/* source/kernel/ref-alder-4690_08.21/linux-5.4

    - run: find source/kernel/ref-alder-4690_08.21/linux-5.4 -name '*.symref'
    
    #- run: KBUILD_PRESERVE=1 make

    - run: grep -v '#  freetz-ng ' .config > config-${{ matrix.box }}

    - run: git checkout make/kernel/configs/freetz/config-ur8-7270_06.05

    - uses: EndBug/add-and-commit@v9
      with:
        push: false
        
    - run: git pull --rebase && git push

    - uses: actions/upload-artifact@v7
      with:
        name: images-${{ matrix.box }}-${{ github.sha }}
        path: images
        retention-days: 2
