$(call PKG_INIT_LIB, 1.11.4)
$(PKG)_LIB_VERSION:=5.5
$(PKG)_SOURCE:=$(pkg)-$($(PKG)_VERSION).tar.xz
$(PKG)_HASH:=8a247f57d1e3e6f6d11413b12a6f28a9d388de110adc0ec608d893180ed7097b
$(PKG)_SITE:=https://github.com/nih-at/libzip/releases/download/v$($(PKG)_VERSION)
### WEBSITE:=https://libzip.org
### MANPAGE:=https://libzip.org/documentation/
### CHANGES:=https://github.com/nih-at/libzip/releases
### CVSREPO:=https://github.com/nih-at/libzip

$(PKG)_BINARY:=$($(PKG)_DIR)/lib/libzip.so.$($(PKG)_LIB_VERSION)
$(PKG)_STAGING_BINARY:=$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libzip.so.$($(PKG)_LIB_VERSION)
$(PKG)_TARGET_BINARY:=$($(PKG)_TARGET_DIR)/libzip.so.$($(PKG)_LIB_VERSION)

$(PKG)_DEPENDS_ON += cmake-host zlib

$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_INSTALL_PREFIX="/"
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_BUILD_TYPE=Release

$(PKG)_CONFIGURE_OPTIONS += -DBUILD_DOC=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_OSSFUZZ=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_REGRESS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_SHARED_LIBS=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TOOLS=OFF

$(PKG)_CONFIGURE_OPTIONS += -DENABLE_COMMONCRYPTO=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_BZIP2=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_GNUTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_LZMA=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_MBEDTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_OPENSSL=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_WINDOWS_CRYPTO=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_ZSTD=OFF

$(PKG)_CONFIGURE_OPTIONS += -DZLIB_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(LIBZIP_DIR)
#cmake	cmake -LAH $(TRANSMISSION_DIR)

$($(PKG)_STAGING_BINARY): $($(PKG)_BINARY)
	$(SUBMAKE) -C $(LIBZIP_DIR) \
		DESTDIR="$(TARGET_TOOLCHAIN_STAGING_DIR)" \
		install
	$(PKG_FIX_LIBTOOL_LA) \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/lib/pkgconfig/libzip.pc
	@touch -c $@

$($(PKG)_TARGET_BINARY): $($(PKG)_STAGING_BINARY)
	$(INSTALL_LIBRARY_STRIP)

$(pkg): $($(PKG)_STAGING_BINARY)

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(LIBZIP_DIR) clean
	$(RM) -r \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/libzip.* \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/zip.h \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/include/zipconf.h \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/pkgconfig/libzip.pc \
		$(TARGET_TOOLCHAIN_STAGING_DIR)/usr/lib/cmake/libzip/

$(pkg)-uninstall:
	$(RM) $(LIBZIP_TARGET_DIR)/libzip.so*

$(PKG_FINISH)
